[[news]]
date = "2025-11"
content = "Our paper [Accumulating Context Changes the Beliefs of Language Models](https://arxiv.org/abs/2511.01805) was featured by [Science](https://www.science.org/content/article/scienceadviser-it-s-surprisingly-easy-change-language-model-s-mind)![Science](/icons/science.png)!"

[[news]]
date = "2025-05"
content = "Graduated from [Princeton University](https://www.princeton.edu/)![Princeton](/icons/princeton.png) and started my PhD at [LTI CMU](https://www.lti.cs.cmu.edu/)![CMU](/icons/cmu.png)!"

[[news]]
date = "2025-05"
content = "Our paper [Mind Your Step (by Step): Chain-of-Thought can Reduce Performance on Tasks where Thinking Makes Humans Worse](https://arxiv.org/abs/2410.21333) has been accepted by ICML 2025!"

[[news]]
date = "2025-01"
content = "Our paper [Large Language Models Assume People are More Rational](https://arxiv.org/abs/2406.17055) has been accepted by ICLR 2025!"

[[news]]
date = "2023-09"
content = "Started my Master study at [Princeton University](https://www.princeton.edu/)![Princeton](/icons/princeton.png)!"
