type = "card"
title = "Teaching"

[[items]]
title = "Multi-agent RL, Safe RL"
subtitle = "Guest Lecturer"
date = "Spring 2025"
content = "Dept. of Computer Science, Princeton University"

[[items]]
title = "Intro to Reinforcement Learning"
subtitle = "Teaching Assistant"
date = "Spring 2025"
content = "Dept. of Computer Science, Princeton University"

[[items]]
title = "Intro to Robotics"
subtitle = "Teaching Assistant"
date = "Fall 2023; Fall 2024"
content = "Dept. of Computer Science, Princeton University"

[[items]]
title = "NNs: Theory and Applications"
subtitle = "Teaching Assistant"
date = "Spring 2024"
content = "Dept. of Computer Science, Princeton University"

[[items]]
title = "Statistics & Probability"
subtitle = "Undergraduate Course Assistant"
date = "Spring 2023"
content = "Dept. of Math and Stats, McGill University"

[[items]]
title = "Applied Regression"
subtitle = "Undergraduate Course Assistant"
date = "Fall 2022"
content = "Dept. of Math and Stats, McGill University"

[[items]]
title = "Linear Algebra"
subtitle = "Undergraduate Course Assistant"
date = "Spring 2022"
content = "Dept. of Math and Stats, McGill University"
